name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create .env
      run: cp .env.example .env
    - name: Install composer
      uses: php-actions/composer@v6
    - name: Install composer dependencies
      run: sudo composer install
    - name: Install and build npm assets
      run: npm install && npm run build
    - name: Run Laravel Sail
      run: ./vendor/bin/sail up -d
    - name: Generate key
      run: ./vendor/bin/sail artisan key:generate
    - name: Run Test
      run: sudo chmod +x test.sh && ./test.sh
    - name: Stop Laravel Sail
      run: ./vendor/bin/sail stop