name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          vendor
        key: ${{ runner.os }}-dependencies
    - name: Install composer
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        docker run --rm \
        -u "$(id -u):$(id -g)" \
        -v $(pwd):/var/www/html \
        -w /var/www/html \
        laravelsail/php81-composer:latest \
        composer install --ignore-platform-reqs
    - name: Install npm dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: npm install
    - name: Build npm assets
      run: npm run build
    - name: Create .env
      run: cp .env.example .env
    - name: Run Laravel Sail
      run: ./vendor/bin/sail up -d
    - name: Generate key
      run: ./vendor/bin/sail artisan key:generate
    - name: Run Test
      run: ./vendor/bin/sail artisan test  # sudo chmod +x test.sh && ./test.sh
    - name: Stop Laravel Sail
      run: ./vendor/bin/sail stop