name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install composer
      uses: php-actions/composer@v6
    - name: Install dependencies
      run: composer install
    - name: Migrate
      run: php artisan migrate:fresh
    - name: Run Laravel
      run: ./vendor/bin/sail up -d